server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.152.128
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI5tKAYaLkJbczKxjbE9FG # 你自己的accessKeyId
    accessKeySecret: QuuPG9pBTJKaMeCYvqM5SyVzIJ0HAB # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_143714980 # 模板名称