server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5 #拉取服务注册信息间隔时间
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/**  #路由到商品的微服务
    search-service: /search/**  #路由到搜索微服务
    user-service: /user/**  #路由到user微服务
    auth-service: /auth/**  #路由到auth微服务
    cart-service: /cart/**  #路由到购物车微服务
  add-host-header: true
  sensitive-headers:  #覆盖敏感头信息
leyou:
  jwt:
    pubKeyPath: E:\\IdeaProjects\\tmp\\rsa\\rsa.pub   # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:   #以下是白名单路径
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item

